### ISSUE TITLE
Crash on Android Lollipop

### ISSUE THREAD

**Issue by dadino** [johnkil/Android-RobotoTextView#33]
I have the following error showing up on the layout preview

    Exception Details java.lang.NullPointerException   at 
    android.content.res.BridgeResources.getAnimation(BridgeResources.java:292)   at 
    android.animation.AnimatorInflater.loadStateListAnimator(AnimatorInflater.java:95)   at 
    android.view.View.<init>(View.java:4016)   at android.widget.TextView.<init>(TextView.java:629)   at 
    android.widget.Button.<init>(Button.java:111)   at android.widget.Button.<init>(Button.java:107)   at 
    android.widget.Button.<init>(Button.java:103)   at 
    com.devspark.robototextview.widget.RobotoButton.<init>(RobotoButton.java:59)   at 
    java.lang.reflect.Constructor.newInstance(Constructor.java:526)   at 
    android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:802)   at 
    android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:64)   at 
    android.view.LayoutInflater.rInflate(LayoutInflater.java:778)   at 
    android.view.LayoutInflater.inflate(LayoutInflater.java:500)   at 
    android.view.LayoutInflater.inflate(LayoutInflater.java:381)

This lead to a crash on the Activity.setContentView()

     Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070067 type #0x1d is not valid
            at android.content.res.Resources.loadXmlResourceParser(Resources.java:2603)
            at android.content.res.Resources.getXml(Resources.java:1098)
            at android.transition.TransitionInflater.inflateTransition(TransitionInflater.java:75)
            at com.android.internal.policy.impl.PhoneWindow.getTransition(PhoneWindow.java:3696)
            at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3649)
            at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:367)
            at android.app.Activity.setContentView(Activity.java:2144)

By looking at the code I think it searches for the animation xml added in Lollipop (for ripple effects and touch related animations).
Is there a way to bypass this exception, without having to rewrite the whole layout for v21?

EDIT: After some testing it appears that the library is not the cause of the crash, instead the style I used for the button is:

      style="?android:buttonBarButtonStyle"
 
The second problem was the android:accentColor in the Material theme being #rrggbb instead of #aarrggbb

**Comment by johnkil** [comment]
Tried to set custom style for the button, everything works correctly without exception. @dadino Could you check for the problem using the latest version of the AppCompat library (21.0.3) and latest version of the RobotoTextView (2.3.0).
